language: generic
sudo: require
services:
    - docker
before.install:
    - docker build -t phfldocker/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true phfldocker/react-test npm test
after_sucess:
    - docker build -t phfldocker/multi-client ./client 
    - docker build -t phfldocker/multi-nginx ./nginx
    - docker build -t phfldocker/multi-server ./server
    - docker build -t phfldocker/multi-worker ./worker
    # docker login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    # take this is image push to docker hub
    - docker push phfldocker/multi-client
    - docker push phfldocker/multi-nginx
    - docker push phfldocker/multi-server
    - docker push phfldocker/multi-worker
    # deploy aws
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-311970152278"
    bucket_path: "docker-multi" 
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
         secure: $AWS_SECRET_KEY
    